### PR TITLE
Toolchain agnostic

### PR DESCRIPTION
**Pull request by zmanian**
Same as #30 but develope instead of master

### CODE REVIEW

**Comment by makufiru** [comment]
I just tried using this on windows with rustup and I get the following error message:

**

> Tokamak: Listing toolchains failed!

**
> rustup 0.1.12 (c6e430a 2016-05-12)
> The Rust toolchain installer
> USAGE:
>     rustup.exe [FLAGS] [SUBCOMMAND]
> FLAGS:
>     -v, --verbose    Enable verbose output
>     -h, --help       Prints help information
>     -V, --version    Prints version information
> SUBCOMMANDS:
>     show         Show the active and installed toolchains
>     update       Update Rust toolchains
>     default      Set the default toolchain
>     toolchain    Modify or query the installed toolchains
>     target       Modify a toolchain's supported targets
>     override     Modify directory toolchain overrides
>     run          Run a command with an environment configured for a given toolchain
>     which        Display which binary will be run for a given command
>     doc          Open the documentation for the current toolchain.
>     self         Modify the rustup installation
>     telemetry    rustup telemetry commands
>     help         Prints this message or the help of the given subcommand(s)
> rustup installs The Rust Programming Language from the official
> release channels, enabling you to easily switch between stable, beta,
> and nightly compilers and keep them updated. It makes cross-compiling
> simpler with binary builds of the standard library for common platforms.
> If you are new to Rust consider running `rustup doc --book`
> to learn Rust.
>

**Comment by zmanian** [comment]
Hmm, it seem like the rustup binary is being triggered on Windows but the "list toolchains" argument isn't being passed to it. 

I know very little able Atom on Windows. Anyone have some ideas?

**Comment by vertexclique** [comment]
@zmanian I want to support Windows actually. But I don't have a testing environment for that.
But those kind of problems can be solved by creating a helper program that detects and switches rust versions via rustup and supply extra data to tokamak...

**Comment by zmanian** [comment]
I'll try and get my hands on a windows testing environment.

**Comment by zmanian** [comment]
I need to do some windows development for dayjob so I'll have access to a windows machine shortly to sort out the windows compatibility issues.

**Comment by ambethia** [comment]
Is it just me or does it seem like development has largely halted on Tokamak?

**Comment by vertexclique** [comment]
Sorry for halted development and late responses.
Because we had a military coup in my country and it is not televised.

**Comment by zmanian** [comment]
@vertexclique stay safe!

**Comment by ambethia** [comment]
@vertexclique I was reading about this earlier today. Yes, please stay safe!

**Pull request merged**
