### PR TITLE
Switch from multirust to rustup as toolchain manager

### PR DESCRIPTION
**Pull request by zmanian**
Not ready for merge. But a functional replacement of multirust with rustup.

How do you want to support rustup in the long run?

### CODE REVIEW

**Comment by vertexclique** [comment]
@zmanian I prefer both together for now. After all things got mature enough we can completely remove multirust implementation. For now if somebody adds rustup feature it would be good.

Here is our talk with @kevinpoitra:
https://github.com/vertexclique/tokamak/issues/5#issuecomment-206049915

**Comment by zmanian** [comment]
Would you be interested if I reformated the pull request to use a config value to decide between multirust and rustup?

Would you prefer a rustup-toolchain-view and multi-rusttool-chain-view file or a single toolchain-view file that does the right thing based on the config file?

**Comment by zmanian** [comment]
Would you be interested in putting RustUp vs Multitrust into a config file?

Would you prefer a rustup file and mulitrust file?

**Comment by vertexclique** [comment]
Just `toolchain-view` will enough I think @zmanian 
Yeah config value will be good, also we can add this to project specific configuration file specific to tokamak. I will call it `.tokamak`.

**Comment by zmanian** [comment]
Close in favor of #30

**Pull request closed without merging**
